agent_id: "qwen3_vl"
agent_kwargs:
  resolution: [720, 1600]
  protocol_kwargs:
    full_history_size: 1
  sampling_kwargs:
    temperature: 0.0

env_id: "phoneworld"
env_kwargs:
  loop_detect: 5
  extra_tools: ["open_app", "response", "terminate"]
